### ISSUE TITLE
m2l_geometry.save_faults

### ISSUE THREAD

**Issue by bluetyson** [Loop3D/map2loop#10]
-- sometimes things will be null, na, in that sense, so possibly can handle that?

if(flt[c_l['fdip']]==c_l['fdipnull']): # null specifc dip defined
                        if(not str(flt[c_l['fdipest']])=='None'): #  dip estimate defined
                            i=0
                            for choice in split:
                                if(flt[c_l['o']]=='-1'):
                                    print(choice)
                                if(choice == flt[c_l['fdipest']]):
                                    fault_dip=int(fault_dip_choices[i+1])
                                    if(flt[c_l['o']]=='-1'):
                                        print('found_dip',fault_dip)
                                i=i+1
                        else:
                            if(fault_dip == -999): # random flag
                                fault_dip=random.randint(60,90)
                    else:
                        print( flt[c_l['fdip']])
                        if flt[c_l['fdip']] == "None" or flt[c_l['fdip']] is None:
                            fault_dip = 90
                        else:
                            fault_dip=int(flt[c_l['fdip']]) # specific dip defined

**Comment by markjessell** [comment]
Yeah, check_map() needs to be expanded so any column that doesn't exist is added, and any field with nulls or 0 where I need stuff is given a default value.

**Comment by markjessell** [comment]
check_map() updated in latest release
