### ISSUE TITLE
gdal not installed with conda install

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop#11]
Trying to run Notebook 1 after conda install...

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/osgeo/__init__.py:30, in swig_import_helper()
     29 try:
---> 30     return importlib.import_module(mname)
     31 except ImportError:

File ~/anaconda3/envs/m2l3_9/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:666, in _load_unlocked(spec)

File <frozen importlib._bootstrap>:565, in module_from_spec(spec)

File <frozen importlib._bootstrap_external>:1173, in create_module(self, spec)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

ImportError: libpoppler.so.126: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 3
      1 import time
      2 import os
----> 3 from map2loop.project import Project
      4 from map2loop.m2l_enums import VerboseLevel, Datatype
      5 from map2loop.sorter import SorterAlpha, SorterAgeBased, SorterUseHint, SorterUseNetworkX, SorterMaximiseContacts, SorterObservationProjections

File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/map2loop/__init__.py:1
----> 1 from .project import Project
      3 __all__ = ["Project"]

File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/map2loop/project.py:3
      1 import beartype
      2 from .m2l_enums import VerboseLevel, ErrorState, Datatype
----> 3 from .mapdata import MapData
      4 from .sampler import Sampler, SamplerDecimator, SamplerSpacing
      5 from .thickness_calculator import ThicknessCalculator, ThicknessCalculatorAlpha

File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/map2loop/mapdata.py:5
      3 import numpy
      4 import shapely
----> 5 from osgeo import gdal, osr
      6 from owslib.wcs import WebCoverageService
      7 import urllib

File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/osgeo/__init__.py:46
     42                 raise ImportError(traceback_string + '\n' + msg)
     43         return importlib.import_module('_gdal')
---> 46 _gdal = swig_import_helper()
     47 del swig_import_helper
     49 __version__ = _gdal.__version__ = _gdal.VersionInfo("RELEASE_NAME")

File ~/anaconda3/envs/m2l3_9/lib/python3.9/site-packages/osgeo/__init__.py:43, in swig_import_helper()
     41         traceback_string = ''.join(traceback.format_exception(*sys.exc_info()))
     42         raise ImportError(traceback_string + '\n' + msg)
---> 43 return importlib.import_module('_gdal')

File ~/anaconda3/envs/m2l3_9/lib/python3.9/importlib/__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

ModuleNotFoundError: No module named '_gdal'

**Comment by RoyThomsonMonash** [comment]
I don't know how map2loop could install without gdal as it's a dependency of geopandas which is a dependency of map2loop.
One thing to check is whether you have conda-forge set as a default channel in conda.

If you are still having this problem Mark can you tell me the steps you used to create the conda environment?

General note: gdal installations can be notorious (to the point that some people recommend you only pip install gdal), I have found the conda-forge repos suitable for gdal in most cases however.

**Comment by markjessell** [comment]
How right you are, I must have missed conda-forge on one of the installs



Mark Jessell
Professor/ Western Australian Fellow
Centre for Exploration Targeting/ SES • M006, Perth WA 6009 Australia
T +61 8 6488 5803 • E ***@***.***

________________________________
