### ISSUE TITLE
[Bug] - dependency versions are not consistent for different installation approaches

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#115]
### Version

N/A

### Bug Description

When installing from source or directly from anaconda the dependencies are not satisfied correctly. 

This is caused because the dependency versions are not listed in the setup.py file or the conda meta.yml file

### Minimal reproducible example

n/a

### Expected Behavior

installing from source or conda should force the packages to fulfil the dependency requirements listed in the packages dependencies.txt file

### Actual Behavior

pip install . will install the most recent version of all packages (regardless of compatibility)
conda install -c loop3d -c conda-forge map2loop will install the most recent versions of the packages.

### Environment

should be the same on all

### Severity

- [ ] Low
- [ ] Medium
- [ ] High
- [X] Critical

**Comment by lachlangrose** [comment]
FYI to get the current notebooks working you need to install using 

`conda install -c conda-forge -c loop3d map2loop==v3.1.8 LoopProjectFile==0.1.3 LoopStructural==v1.6.0 jupyter -y
`

**Comment by lachlangrose** [comment]
Also add map2model to pypi

**Comment by AngRodrigues** [comment]
I think this will be solved now with v3.2. 
Installations steps have also been updated with PR #167
