### ISSUE TITLE
Two supergoups picked for turner syncline 

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#12]
Dataset is attached.

When run on Linux using latest version of map2loop I get two supergroups for the turner syncline model. 

super_groups= [['Hamersley Group', 'Turee Creek Group'], ['Fortescue Group']]

mplstereonet is version 0.5

[Turner_Syncline.zip](https://github.com/Loop3D/map2loop/files/4802303/Turner_Syncline.zip)

**Comment by markjessell** [comment]
Ok, I am using mplstereonet version 0.6-dev

That may be the issue?

m
