### ISSUE TITLE
[Feature Request] - Add map2loop to pypi 

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#128]
### 💻

- [ ] Would you like to work on this feature?

### Feature Description

Add map2loop to pypi

### Current Situation

it is not on pypi

### Proposed Solution

Add the required steps to the github action yml file to upload to pypi. I have authorised the release-please.yml workflow to upload to pypi from the loop3d/map2loop repository. 

https://github.com/Loop3D/loopstructural-visualisation/edit/main/.github/workflows/release.yml should be a good template for how to do this

### Affected Areas

- [ ] input data
- [ ] project creation
- [ ] samplers
- [ ] sorters
- [ ] stratigraphic column
- [ ] data types
- [X] Other

**Comment by lachlangrose** [comment]
This is related to #130 and #115

**Comment by AngRodrigues** [comment]
- [ ] need to fix what seems to be an authentication issue with Pypi
