### ISSUE TITLE
[Question] - Geological Library for Phython and Step by Step Methodology for creation of 3D models

### ISSUE THREAD

**Issue by vanitpatelfr** [Loop3D/map2loop#129]
### Question Details

1. Which Geological Library in Python will be more pertinent to use??
2. Is there any methodology or steps to be followed for the creation of 3D Geological models using Python?? The Python codes are available, but steps/methodology will be more useful towards the creation of the 3D Geological model.

**Comment by AngRodrigues** [comment]
Hi @vanitpatelfr, 

1. map2loop is pertinent to use for cases in which the user wants to convert a geological map (composed of at least two shapefiles containing: 1. geological polygons and 2. geological structures) into inputs for geological modelling. You can check the library's functionality by referring to [this](https://gmd.copernicus.org/articles/14/5063/2021/) paper. [LoopStructural](https://github.com/Loop3D/LoopStructural) is the Python library that is pertinent to use for 3D implicit geological modelling; [this](https://gmd.copernicus.org/articles/14/3915/2021/) and [this](https://gmd.copernicus.org/articles/14/6197/2021/) paper highlight some of the LoopStructural functionality. 

2. [LoopStructural](https://github.com/Loop3D/LoopStructural) can be used for 3D implicit geological modelling. The documentation is [here](https://loop3d.org/LoopStructural/). 

Map2loop has a [series of jupyter notebooks](https://github.com/Loop3D/map2loop-notebooks/tree/master) that show how to deconstruct map data (with map2loop) as an input to develop a geological model (LoopStructural). Please let us know if you have any questions about those notebooks, or the [map2loop documentation](https://loop3d.org/map2loop/). If you have a specific question about LoopStructural, please feel free to [post a question on that repo](https://github.com/Loop3D/LoopStructural/issues/new?assignees=&labels=&projects=&template=questions-.md&title=%5BQuestion%5D).

**Comment by vanitpatelfr** [comment]
Thanks a lot for answering the query.
