### ISSUE TITLE
map2loop to LoopStructural: versions conflicts or not installed properly?

### ISSUE THREAD

**Issue by polyye** [Loop3D/map2loop#13]
When I try to use my map2loop outputs in LoopStructural I get an error. Is this because I didn't install LoopStructural properly? Or maybe conflicts because of different versions?

when I do this:

`from LoopStructural import GeologicalModel
`

I get:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
m2l_config_remote_Paterson.py in <module>
      1 ##Check
      2 
----> 3 from LoopStructural import GeologicalModel

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\__init__.py in <module>
     20 import tempfile
     21 from pathlib import Path
---> 22 from .modelling.core.geological_model import GeologicalModel
     23 from .visualisation.model_visualisation import LavaVuModelViewer
     24 from .visualisation.map_viewer import MapView

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\modelling\core\geological_model.py in <module>
      5 
      6 from LoopStructural.datasets import normal_vector_headers
----> 7 from LoopStructural.interpolators.discrete_fold_interpolator import \
      8     DiscreteFoldInterpolator as DFI
      9 from LoopStructural.interpolators.finite_difference_interpolator import \

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\interpolators\__init__.py in <module>
     25 
     26 """
---> 27 from LoopStructural.interpolators.discrete_fold_interpolator import DiscreteFoldInterpolator
     28 from LoopStructural.interpolators.finite_difference_interpolator import \
     29     FiniteDifferenceInterpolator

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\interpolators\discrete_fold_interpolator.py in <module>
      4 from LoopStructural.interpolators.cython.dsi_helper import fold_cg
      5 
----> 6 from LoopStructural.interpolators.piecewiselinear_interpolator import \
      7     PiecewiseLinearInterpolator
      8 

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\interpolators\piecewiselinear_interpolator.py in <module>
      5 from LoopStructural.interpolators.discrete_interpolator import \
      6     DiscreteInterpolator
----> 7 from LoopStructural.utils.helper import get_vectors
      8 
      9 logger = logging.getLogger(__name__)

~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\LoopStructural\utils\helper.py in <module>
      2 
      3 import numpy as np
----> 4 from sklearn.decomposition import PCA
      5 
      6 logger = logging.getLogger(__name__)

ModuleNotFoundError: No module named 'sklearn'

**Comment by markjessell** [comment]
scikit-learn is not installed, so assuming you are in the loop env, type:

conda install -c anaconda scikit-learn

you may also get the same error with scikit-image, in which case :

conda install -c anaconda scikit-image


in general if you get a ModuleNotFoundError: No module named xxx error, simply google “conda install xxx” to see if there is a simple solution. If that fails, try to google “pip install xxx”
cheers

mark
