### ISSUE TITLE
[Bug] - LPF error using example notebook #3

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop#130]
### Version

Did clean install via conda today

### Bug Description

when running notebook Example 3 - Local Source Data

it crashes as follows

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 81
     64 # Or you can run map2loop and pre-specify the stratigraphic column
     65 column = [
     66     # youngest
     67     'Turee_Creek_Group',
   (...)
     79     # oldest
     80 ]
---> 81 proj.run_all(user_defined_stratigraphic_column=column)
     83 # Or you can get map2loop to run all column sorting algorithms it has and takes the one
     84 # that has the longest total basal contact length
     85 #proj.run_all(take_best=True)
     86 proj.run_all()

File [~/anaconda3/envs/loop924/lib/python3.10/site-packages/map2loop/project.py:438](http://localhost:8889/lab/tree/anaconda3/envs/loop924/lib/python3.10/site-packages/map2loop/project.py#line=437), in Project.run_all(self, user_defined_stratigraphic_column, take_best)
    436 self.summarise_fault_data()
    437 self.apply_colour_to_units()
--> 438 self.save_into_projectfile()

File [~/anaconda3/envs/loop924/lib/python3.10/site-packages/map2loop/project.py:471](http://localhost:8889/lab/tree/anaconda3/envs/loop924/lib/python3.10/site-packages/map2loop/project.py#line=470), in Project.save_into_projectfile(self)
    469 # Save extents
    470 if existing_extents is None:
--> 471     LPF.Set(self.loop_filename, "extents", geodesic=[-180, -179, 0, 1],
    472             utm=[1,
    473                  1,
    474                  self.map_data.bounding_box["minx"],
    475                  self.map_data.bounding_box["maxx"],
    476                  self.map_data.bounding_box["miny"],
    477                  self.map_data.bounding_box["maxy"]
    478                  ],
    479             depth=[
    480                  self.map_data.bounding_box["top"],
    481                  self.map_data.bounding_box["base"]
    482                  ],
    483             spacing=[1000, 1000, 500],
    484             preference="utm"
    485             )
    486 else:
    487     # TODO: Check loopfile extents match project extents before continuing
    488     # if mismatch on extents warn the user and create new file
    489     LPF.Set(self.loop_filename, "extents", **existing_extents)

File ~/.local/lib/python3.10/site-packages/LoopProjectFile/LoopProjectFile.py:243, in Set(filename, element, **kwargs)
    241     response = Version.SetVersion(root, **kwargs)
    242 elif element == "extents":
--> 243     response = Extents.SetExtents(root, **kwargs)
    244 elif element == "strModel":
    245     response = StructuralModels.SetStructuralModel(root, **kwargs)

TypeError: SetExtents() missing 1 required positional argument: 'epsg'

### Minimal reproducible example

run cell 2 of Example 3 - Local Source Data

### Expected Behavior

not to crash

### Actual Behavior

Crashes

### Environment

WSL 2: Linux mark-Z490-AORUS-MASTER.uniwa.uwa.edu.au 6.5.0-35-generic #35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Severity

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Critical

**Comment by lachlangrose** [comment]
@markjessell can you confirm which version of map2loop and looprojectfile were have installed - I guess 3.0.1 and 0.1. I think map2loop hasn't installed 3.1.11 because the version has changed from 3.0.1 to v3.1.11 and the non v version is seen as a higher version by conda.

**Comment by lachlangrose** [comment]
This is the same issue as #115

**Comment by markjessell** [comment]
I just did another clean install using conda and the versions are:

loopprojectfile           0.1.4                    pypi_0    pypi
loopstructural            1.6.2                    pypi_0    pypi
map2loop                  3.0.6                    pypi_0    pypi
map2model                 1.2.0                    pypi_0    pypi

I tried pip just now but I don't think it has synced yet as it gave me a really old version of map2loop...

**Comment by lachlangrose** [comment]
Yeah, pip won't work #115 hasn't been looked at yet. 

Can you try conda install -c conda-forge -c loop3d "map2loop==v3.1.11"

**Comment by rabii-chaarani** [comment]
You should use loopprojectfile 0.1.3 with map2loop 3.1.11, as version 0.1.4 has a problem saving the project file. 

> I just did another clean install using conda and the versions are:
> 
> loopprojectfile 0.1.4 pypi_0 pypi loopstructural 1.6.2 pypi_0 pypi map2loop 3.0.6 pypi_0 pypi map2model 1.2.0 pypi_0 pypi
> 
> I tried pip just now but I don't think it has synced yet as it gave me a really old version of map2loop...

**Comment by AngRodrigues** [comment]
Will close this now, as we're actively working on the existing installation issues.
