### ISSUE TITLE
[Feature Request] - change map2loop versioning to not have v tag

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#131]
### 💻

- [ ] Would you like to work on this feature?

### Feature Description

As title

### Current Situation

.

### Proposed Solution

.

### Affected Areas

- [ ] input data
- [ ] project creation
- [ ] samplers
- [ ] sorters
- [ ] stratigraphic column
- [ ] data types
- [X] Other

**Comment by AngRodrigues** [comment]
@lachlangrose just confirming that this is a request to remove the "v" in the version tag?
Thanks

**Comment by lachlangrose** [comment]
@AngRodrigues it doesn't matter if there is a v tag or if there is no v tag but we can't have both. Conda prioritises packages that don't have the v tag. I think @rabii-chaarani renamed all of the old map2loop conda packages to have a v-tag. If conda install -c conda-forge -c loop3d map2loop results in the current latest version being installed then its ok to leave

**Comment by AngRodrigues** [comment]
@lachlangrose that makes sense, thanks for providing further information. We'll look into this.

**Comment by AngRodrigues** [comment]
All map2loop distributions without -v have been added a -v in the [loop3d channel](https://anaconda.org/loop3d/map2loop/files). 
All future distributions should have the -v tag, a feature that should now be controlled by the current [release-please-config.json](https://github.com/Loop3D/map2loop/blob/master/release-please-config.json)
