### ISSUE TITLE
Error in creating stratigraphic sets per group

### ISSUE THREAD

**Issue by polyye** [Loop3D/map2loop#15]
In the **_1. WA leaflet example notebook_**, in section **_Create possible stratigraphy sets per group_**, when I type this:

`m2l_topology.save_group(G,tmp_path,glabels,geol_clip,c_l)`

I get this error:

> ParserError                               Traceback (most recent call last)
> m2l_config_remote_Paterson.py in <module>
> ----> 1 m2l_topology.save_group(G,tmp_path,glabels,geol_clip,c_l)
> 
> ~\AppData\Roaming\Python\Python38\site-packages\map2loop-0.0.50-py3.8.egg\map2loop\m2l_topology.py in save_group(G, path_out, glabels, geol, c_l)
>     215     #display(geology_file)
>     216 
> --> 217     gp_ages = pd.read_csv(path_out+'age_sorted_groups.csv')
>     218     #display(gp_ages)
>     219     gp_ages.set_index('group_',  inplace = True)
> 
> ~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\pandas\io\parsers.py in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)
>     684     )
>     685 
> --> 686     return _read(filepath_or_buffer, kwds)
>     687 
>     688 
> 
> ~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\pandas\io\parsers.py in _read(filepath_or_buffer, kwds)
>     456 
>     457     try:
> --> 458         data = parser.read(nrows)
>     459     finally:
>     460         parser.close()
> 
> ~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
>    1184     def read(self, nrows=None):
>    1185         nrows = _validate_integer("nrows", nrows)
> -> 1186         ret = self._engine.read(nrows)
>    1187 
>    1188         # May alter columns / col_dict
> 
> ~\AppData\Local\Continuum\anaconda3\envs\loop\lib\site-packages\pandas\io\parsers.py in read(self, nrows)
>    2143     def read(self, nrows=None):
>    2144         try:
> -> 2145             data = self._reader.read(nrows)
>    2146         except StopIteration:
>    2147             if self._first_chunk:
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader.read()
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_low_memory()
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._read_rows()
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.TextReader._tokenize_rows()
> 
> pandas\_libs\parsers.pyx in pandas._libs.parsers.raise_parser_error()
> 
> **ParserError: Error tokenizing data. C error: Expected 5 fields in line 7, saw 6**

Could be something wrong with the **geol_clip**? More columns than the expected for a specific row?
How to fix that?

**Comment by polyye** [comment]
I found the error... in the ages_sorted_group.csv one of the groups containing underscore/space in it is being split into 2 columns such as that there's one more column that the expected for this row, creating the error.

**Comment by markjessell** [comment]
Thanks, I have stiuck an extra test in the check_map() code which is where I try to make sure that the input files are fit for purpose. It will appear in a future update.
