### ISSUE TITLE
[bug] changing map data config does not work

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#15]
Updating any map_data config does not seem to work
e.g.

```
proj.map_data.config.geology_config["intrusive_text"] = "IGNEOUS"
```

Map data is loaded in the init function of the project, I guess its not reloaded when run is called. 

I think this is related to #13 and the config file maybe needs to be an attribute of the project that is watched and then when it changes trigger a reload of the map data?

@RoyThomsonMonash any ideas?

**Comment by RoyThomsonMonash** [comment]
Setting a config variable via that method doesn't indicate that the map needs to be reloaded.  Either a setter at the project level needs be to created that also "dirties" the geology map or you can dirty that map specifically:
proj.map_data.dirtyflags[Datatype.GEOLOGY] = True
For a good example of a setter look at proj.set_ignore_codes which calls proj.map_data.set_ignore_codes
