### ISSUE TITLE
[Bug] - map2loop allows incorrect arguments to be passed to the set_sampler function 

### ISSUE THREAD

**Issue by ayLa-e** [Loop3D/map2loop#155]
### Version

m2l version= 3.1.13 

### Bug Description

map2loop allows users to pass a sampler rather than a decimator as an argument to the proj.set_sampler function as shown below:   

_**proj.set_sampler(Datatype.STRUCTURE, SamplerSpacing(100.0))**_

In this example the argument should be _**SamplerDecimator(1)**_ not _**SamplerSpacing(100.0)**_

This produces a "_KeyError: 'layerID_' " runtime error message when run and will prevent structural data from being input into the project file. 

### Minimal reproducible example

Using the following line of code to set the structural samplers for map2loop:

proj.set_sampler(Datatype.STRUCTURE, SamplerSpacing(100.0))

### Expected Behavior

Passing the wrong argument type should result in an exception with an appropriate error message to notify users of their mistake. 

### Actual Behavior

The user is not currently notified, other than receiving a cryptic python "KeyError: 'layerID' " error message. 

### Environment

Windows Version 10.0.22621.3593, Anaconda, Jupyter notebook 

### Severity

- [ ] Low
- [X] Medium
- [ ] High
- [ ] Critical

**Comment by lachlangrose** [comment]
I think this could be fixed by separating the samplers for lines and points then doing a class check on the sampler type. I never understood why lines and points used the same class name as they are different problems.

**Comment by AngRodrigues** [comment]
> I think this could be fixed by separating the samplers for lines and points then doing a class check on the sampler type. I never understood why lines and points used the same class name as they are different problems.

A quick fix for the bug described in this issue has been added in #156  
It's a good idea to separate lines and points; will add that to a feature request to work on in the future.
