### ISSUE TITLE
[bug] igneous_text checks rock type1 not description

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#16]
Currently checking rocktype to determine if a unit is an intrusion. Is this different behaviour to previous versions @markjessell @RoyThomsonMonash ?
```
if config["rocktype_column"] in self.raw_data[Datatype.GEOLOGY]:
            geology["INTRUSIVE"] = (
                self.raw_data[Datatype.GEOLOGY][config["rocktype_column"]]
                .astype(str)
                .str.contains(config["intrusive_text"])
            )
            geology["ROCKTYPE1"] = self.raw_data[Datatype.GEOLOGY][
                config["rocktype_column"]
            ].astype(str)
        else:
            geology["INSTRUSIVE"] = False
            geology["ROCKTYPE1"] = ""
```

**Comment by lachlangrose** [comment]
It also doesn't seem like the contact between intrusives and the other rocks are ignored for the basal contacts.

**Comment by AngRodrigues** [comment]
The current behavior is: the contacts between intrusives and other rocks are ignored in basal contacts. Possibly this issue was  relating to previous versions, so closing this now.
