### ISSUE TITLE
[Bug] - Error to create .loop3d during proj.run()

### ISSUE THREAD

**Issue by ShebMichel** [Loop3D/map2loop#160]
### Version

map2loop                3.1.12
map2model               1.2.0
LoopProjectFile         0.1.3

### Bug Description

The "Error: No columns to parse from file" comes after running proj.run_all(user_defined_stratigraphic_column=None, take_best=True). The function creates all map2loop except the local_source.loop3d file. 

### Minimal reproducible example

N/A

### Expected Behavior

I have tried a different dataset, it does work, I think there may be a try and except need to be added in the function if no parsing is not possible or not necessary.

### Actual Behavior

The function run and because of takes time it crashes, which is not expected especially when using different datasets. 

### Environment

Docker container in windows

### Severity

- [ ] Low
- [ ] Medium
- [X] High
- [ ] Critical

**Comment by AngRodrigues** [comment]
@ShebMichel I just tried to reproduce this, and no error pops up. 
Please go ahead and post a minimum reproducible example with code and data so we can look at this.

**Comment by AngRodrigues** [comment]
@ShebMichel are you still getting this error?

**Comment by ShebMichel** [comment]
@AngRodrigues, tried and still. but other data works. I guess now that I am restructuring the plugin, I will let this bug sleep for now.

**Comment by AngRodrigues** [comment]
Cool, let me know if at any stage you'd like to reopen this.
