### ISSUE TITLE
Hammersley Test orientations

### ISSUE THREAD

**Issue by bluetyson** [Loop3D/map2loop#2]
Started running that, got my first error :- 

All observations n= 121
groups ['Hamersley Group' 'Fortescue Group' 'A-mgn-PRK' 'Turee Creek Group'
 'A-b-PRK' 'A-mgn-PMI' 'A-s-PMI' 'A-s-PRK' 'Shingle Creek Group'
 'Wyloo Group'] 
codes ['A-HAm-cib' 'A-FOp-bs' 'A-HAS-xsl-ci' 'P_-HAb-cib' 'P_-HAj-xci-od'
 'A-mgn-PRK' 'A-FOh-xs-f' 'A-FOo-bbo' 'A-FO-od' 'A-HAd-kd' 'A-FOj-xs-b'
 'P_-TKa-xs-k' 'P_-HAo-ci' 'P_-HAw-fr' 'A-FO-xo-a' 'A-b-PRK' 'A-FOr-b'
 'A-FOu-bbo' 'P_-TK-s' 'A-mgn-PMI' 'A-s-PMI' 'A-s-PRK' 'P_-SKq-stq'
 'P_-WYm-sp' 'P_-WYa-st' 'P_-WYd-kd' 'P_-TKo-stq' 'P_-TKk-sf' 'P_-SKb-bb']

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\OneDrive - OZ Minerals\Exploration\Research\gostin\map2loop\test_data3\m2l_config.py in <module>
      7 if(len(orientations)<2):
      8     raise NameError('Not enough orientations to complete calculations (need at least 2)')
----> 9 group_girdle=m2l_utils.plot_bedding_stereonets(orientations,geology,c_l)

**Comment by markjessell** [comment]
No doubt the first of many!

Can you try getting the latest version from github  as I have improved the way I decide what groups should be put into a super_group (stratigraphic groups that share a common structural history) and I think that may solve this. If not let me know which Notebook you are running please.

**Comment by bluetyson** [comment]
It is the 1 Hammersley notebook  thanks for the help.

**Comment by bluetyson** [comment]
mplstereonet version 0.6 from GitHub worked for this part, so that one is good if you put that in the setup info.

**Comment by markjessell** [comment]
good idea., thanks
