### ISSUE TITLE
Consider removing the fixed geopandas version and update the numpy version

### ISSUE THREAD

**Issue by RoyThomsonMonash** [Loop3D/map2loop#21]
- The geopandas version was restricted to 0.12.2 as we were supported python 3.7 and 3.8.  As python versions progress we should remove the geopandas restriction.

- At the moment we do not specify which numpy version to use and it tends to default to 1.22 which is causing issues with python 3.11.  When we remove the geopandas restriction we should force a newer numpy version

**Comment by AngRodrigues** [comment]
Removed python 3.7 and 3.8 so no longer an issue.
