### ISSUE TITLE
1. Hamersley map processing gempy2 test cell attribute error

### ISSUE THREAD

**Issue by bluetyson** [Loop3D/map2loop#3]
The vertical exageration is:  11.70125
Active grids: ['regular']
Cropped raster to geo_model.grid.extent.
depending on the size of the raster, this can take a while...
storing converted file...
Active grids: ['regular' 'topography']

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
m2l_config.py in <module>
      7 
      8     vtk=False
----> 9     m2l_export.loop2gempy(test_data_name,tmp_path,vtk_path,output_path+'orientations_clean.csv',
     10                                     output_path+'contacts_clean.csv',tmp_path+'groups_clean.csv',
     11                                     bbox,model_base, model_top,vtk,dtm_reproj_file)

~\OneDrive - OZ Minerals\Exploration\Research\gostin\map2loop\map2loop\m2l_export.py in loop2gempy(test_data_name, tmp_path, vtk_path, orientations_file, contacts_file, groups_file, bbox, model_base, model_top, vtk, dtm_reproj_file, va, verbose, compute)
   1013 
   1014         # Rescaling topography:
-> 1015         geo_model.grid.topography.values[:, 2] *= va
   1016         geo_model.grid.update_grid_values()
   1017         geo_model.update_from_grid()

~\AppData\Local\Continuum\anaconda3\envs\gempy\lib\site-packages\gempy\core\model.py in __getattr__(self, item)
     33             return getattr(self._w, item)
     34         else:
---> 35             raise AttributeError(item)
     36 
     37 

AttributeError: topography

**Comment by markjessell** [comment]
Hi. I hadn't updated my gempy since March, so now I have via pip install, and I get a different (theano compilation error) error using gempy. In both cases it is failing within gempy, so as they say (at least in our house) "Not my fault, Kitty". I would hand-ball that to Miguel?

**Comment by bluetyson** [comment]
Right, will see what he says, thanks Mark.

**Comment by markjessell** [comment]
OK, I'll leave this open in case he hand-balls it back to me!
