### ISSUE TITLE
1. map2loop leaflet example Leaflet  - test_data_name

### ISSUE THREAD

**Issue by bluetyson** [Loop3D/map2loop#4]
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
m2l_config_remote.py in <module>
      7 
      8     vtk=False
----> 9     m2l_export.loop2gempy(test_data_name,tmp_path,vtk_path,output_path+'orientations_clean.csv',
     10                                     output_path+'contacts_clean.csv',tmp_path+'groups_clean.csv',
     11                                     bbox,model_base, model_top,vtk,dtm_reproj_file)

NameError: name 'test_data_name' is not defined

-- looks like you just need to give a default name (and for the geomodeller one too I imagine.  Other than that, ran fine (barring Microsoft edge not liking ipyleaflet map displaying),  The gempy issue Miguel said he might look at on the weekend for the notebook case.

**Comment by markjessell** [comment]
test_data_name is defined in Cell #2, did you jump into the notebook halfway without choosing  map area?          test_data_name=map_choice.value

**Comment by markjessell** [comment]
likewise for the choice of engine. Select the choice from the menu then click in the cell below and continue...

**Comment by bluetyson** [comment]
Will check, cell engine was certainly fine!

**Comment by bluetyson** [comment]
In Hamersley it was defined there, not this one? 1. map2loop leaflet example

**Comment by markjessell** [comment]
just sent you a zoom link if you have the time

**Comment by bluetyson** [comment]
Next trick will be to try and make a new dataset which would be good to ask
about.

**Comment by markjessell** [comment]
Basic help from the readme on what the minimum data requirements are:

Minimum map2loop inputs:  
  
1.	EPSG coordinate reference system for input data (metre-based projection like UTM)   
   
2.	Max/min coordinates of area of interest   
   
3.	Geology polygons:   
-a.	All polygons are watertight   
-b.	Polygons stop on faults   
-c.	Polygons have as attributes:   
-i.	Object ID   
-ii.	Stratigraphic code   
-iii.	Stratigraphic group   
-iv.	One of more fields that describe if sill, if igneous, if volcanic   
-v.	    Min_age field   
-vi.	Max_age field (can be same as Min_age field, and can be simple numerical ordering (bigger number is older))   
   
4.	Fault/Fold Axial Trace Polylines:   
-a.	Faults terminate on other faults but do not cross   
-b.	Faults/Folds have as attributes:   
-i.	Object ID   
-ii.	Field that determines if polyline is fault or fold axial trace   
-iii.	Field that determine type of fold axial trace e.g. syncline or anticline)
-iv.    Faults can have dip/dip direction info   
   
5.	Bedding orientations:   
-a.	Assumes dip/dip direction or dip/strike data   
-b.	Orientations have as attributes:   
-i.	Dip   
-ii.	Dip Direction or strike
