### ISSUE TITLE
Naming convention for super_groups.csv inconsistent with all_sorts.csv

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/map2loop#5]
Supergroup name convention is different from the code given in all_sorts.csv e.g. in super_groups.csv spaces are used, in all_sorts _ is used instead: Wyloo Group is "Wyloo_Group" in all_sorts and "Wyloo Group" in super_groups.csv
hyphen is replaced with underscore as well. 

All sorts                                Super_groups
Shingle_Creek_Group -> Shingle Creek Group
Turee_Creek_Group -> Turee Cree Group
Hamersley_Group -> Hamersley Group
Fortescue_Group -> Fortescue Group
A_s_PMI -> A-s-PMI
A_mgn_PMI -> A-mgn-PMI
A_mgn_PRK -> A-mgn-PRK
A_s_PRK -> A-s-PRK
A_b_PRK -> A-b-PRK

**Comment by markjessell** [comment]
Its not a bug its a feature! Geomodeller doesn't like spaces or hyphens, but the original GSWA maps have them, so depending where I am in the process, both conventions need to be supported. The interpolation code goes back to the (undecimated) source vector layers to get its info, so it is easier (for me) to keep the shapefile/wfs format. It should work as is, but if you want I can easily convert them (but so can you) ;)
