### ISSUE TITLE
m2l_topology and data fields

### ISSUE THREAD

**Issue by bluetyson** [Loop3D/map2loop#7]
trying a new one that I hadn't checked the data carefully on, ran into the good old comma in data fields problem (formation names used from GA), which I have hacked for now.  Maybe put a note in data prep to remind about that, to get rid of them first before you start.

    slist=sorted(ages,key=lambda l:l[3])
    f=open(tmp_path+'age_sorted_groups.csv','w')
    f.write('index,group_,min,max,ave\n')
    
    for j in range(0,len(slist)):
        f.write(str(j)+','+slist[j][0]+','+str(slist[j][1])+','+str(slist[j][2])+','+str(slist[j][3])+'\n')
    f.close()

**Comment by markjessell** [comment]
yeah, I actually check for that for the formations, but I forgot to put in a line to check for groups too, updating now. It just gives an error but I may change it to replacing the comma with a space in the future.
